name: Scheduled Scrapers

on:
  schedule:
    - cron: '42 7 * * 1'  # UTC 时间 07:42（对应加州时间 00:42 夏令时）
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies directly
      run: |
        pip install requests beautifulsoup4  # 直接安装所需套件

    - name: Run Club Scraper
      run: python scrapers/club_scraper.py  # 直接运行爬虫

    - name: Run Calendar Scraper
      run: python scrapers/calendar_scraper.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git commit -m "Auto-update: $(date +'%Y-%m-%d')"
        git push
