name: Scheduled Scrapers

on:
  schedule:
    - cron: '42 7 * * 1'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false


    - name: Show working directory and contents
      run: |
        pwd
        ls -al

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}
        ls -al
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Calendar Scraper
      run: python scrapers/calendar_scraper.py
      
    - name: Run Club Scraper
      run: python scrapers/club_scraper.py
      
    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.PAT }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/calendar.json data/clubs_by_category.json
        git commit -m "Auto-update: Club and calendar data" || echo "Nothing to commit"
        git pull --rebase origin main
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
