name: Scheduled Scrapers

on:
  schedule:
    - cron: '42 7 * * 1'  # UTC 時間 07:42（加州時間 00:42 夏令時）
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Club Scraper
      run: |
        cd scrapers
        python club_scraper.py
        cd ..

    - name: Run Calendar Scraper
      run: |
        cd scrapers
        python calendar_scraper.py
        cd ..

    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git commit -m "Auto-update: $(date +'%Y-%m-%d')"
        git push
